### ISSUE TITLE
Resistor gets shifted on save/load

### ISSUE THREAD

**Issue by drahnr** [drahnr/oregano#115]
...

**Comment by gtrentalancia** [comment]
This issue is not fixed !

Rotated components still get shifted. And it doesn't affect only resistors, but other components too (e.g. capacitors, ...).

In the current code, there is a further degradation of the problem introduced by using uninitialized variables, see for example:

https://github.com/gtrentalancia/oregano/commit/c0c2d8c00dc5a23bfc2041e7370d29648b3a6f99
