### ISSUE TITLE
Simulation empty? v0.7.0

### ISSUE THREAD

**Issue by lope** [drahnr/oregano#141]
Hi, here's a noob question. I've got oregano 0.7.0 installed (packaged with Ubunty 14.04 or linux mint 17 etc)

I made a basic schematic. http://wikisend.com/download/860420/test.oregano

I clicked Run a simulation and I get this empty window
http://i.imgur.com/mYLptDs.png

I've got gnucap and ngspice installed.

**Comment by drahnr** [comment]
0.70.y is a totally outdated version, this also was a known bug and is fixed in the latest releases 0.82.x and up.

---

If you can provide the appropriate packaging info to package it, I would actually consider providing prepackaged debian packages (or just a link to debian/ubuntu upstream packaging information, like the files required to describe the package). Open a new bug for debian packaging.
