### ISSUE TITLE
Tests freeze in CI env

### ISSUE THREAD

**Issue by drahnr** [drahnr/oregano#182]
### Steps to reproduce
1. Just commit something
2. check the compile step `https://ci.spearow.io/teams/main/pipelines/oregano/jobs/compile/builds/106`

### Expected behaviour
Success, exit 0

### Actual behaviour
Spins forever, basic watcher test

**Comment by drahnr** [comment]
Maybe adding a timeout to all `GMainLoop`s running `g_main_loop_run(...)` would be enough

**Comment by Michi1994** [comment]
I don't think it's a loop problem. I carefully coded them so that they terminate normally by a chain of events.

I think it's a path resolving problem. I think the system can't find the path to the `expected.txt` file because there appears no `/oregano` string in the path (instead there is `/git-clone-resource`). I think the problem occurs in `static gchar* test_engine_ngspice_get_test_dir_base()`.

**Comment by Michi1994** [comment]
How do I commit something?

**Comment by Michi1994** [comment]
Why are the tests not executed in [https://ci.spearow.io/teams/main/pipelines/oregano/jobs/compile-pr/builds/54](https://ci.spearow.io/teams/main/pipelines/oregano/jobs/compile-pr/builds/54)?

**Comment by drahnr** [comment]
I'll fix that

**Comment by drahnr** [comment]
I fixed the CI to always execute the tests.

The fix did not change anything.
It is not a path problem, the execution path changed to `./build/src/microtests`.
I think it would make senso to make those files includes (or `GResouces`, but that would require some more work and adjustment of the buildsystem which I am not exactly sure is worth it)

**Comment by drahnr** [comment]
Changes to the CI are tracked in this git repository but I have to manually push them.

**Comment by drahnr** [comment]
https://ci.spearow.io/teams/main/pipelines/oregano/jobs/compile/builds/108
